### ISSUE TITLE
[Issue] Backpacks not syncing

### ISSUE THREAD

**Issue by allenclan23** [AuraDevelopmentTeam/InvSync#45] opened 2019-07-05 19:12 UTC
#### Issue Description:
When transferring between my servers, the items inside of a Backpack from the Backpack mod do not transfer. 

#### What happens:
The items do not appear, but show up when i go back to the server that i placed the items in it

#### What you expected to happen:
The items inside would transfer

#### Steps to reproduce:

1. Place items into a backpack
2. Connect to another server on the network
3. Check backpack
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- InvSync: 0.6.19.298-DEV
- Sponge: 7.1.6-RC3616
- Other related mods:
- Backpack: 3.0.2

**Comment by BrainStone** [comment] 2019-07-05 19:15
As mentioned in Discord, please try it again with SpongeForge 7.1.**7**

**Comment by BrainStone** [comment] 2019-07-05 19:16
Duplicate of #40

**Closed by BrainStone** 2019-07-05 19:16 UTC
Labels: bug, duplicate
