### ISSUE TITLE
mysql connect

### ISSUE THREAD

**Issue by 879492767** [AuraDevelopmentTeam/InvSync#29] opened 2018-08-01 15:16 UTC
The latest version of sponge will prompts you not to keep connected

- Minecraft: 1.12.2
- InvSync-0.6.17
- spongeforge-1.12.2-2705-7.1.0-BETA-3361

https://pastebin.com/JBKSrBXP

**Comment by BrainStone** [comment] 2018-08-01 17:31
First of all, it’s a duplicate of #28. Second it’s just a warning that I improperly used the database driver. It does not mean that connections shouldn’t be open. That would be stupid.

**Closed by BrainStone** 2018-08-01 17:31 UTC
