### ISSUE TITLE
Botania flower bag contents are lost

### ISSUE THREAD

**Issue by bluelightning32** [AuraDevelopmentTeam/InvSync#37] opened 2019-03-16 09:49 UTC
#### Issue Description:
On logoff, InvSync is not persisting the contents of the botania flower bag, when the bag is directly in the player's inventory. The player.dat file has the bag contents. When the player logs back in, their inventory is loaded from the InvSync database, and the bag contents are lost.

The flower bag contents are not lost if it is inside of a backpack.

#### Steps to reproduce:

1. Install botania
2. Get a flower bag
3. Put a flower in the flower bag
4. Log off
5. Log in.

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: forge-1.12.2-14.23.5.2807-universal.jar
- InvSync: InvSync-0.6.19.280-DEV.jar
- Sponge: aaaa-spongeforge-1.12.2-2768-7.1.6-RC3596.jar
- Modpack: DD&SS version 4.7
- Other related mods: 
```
> /sponge plugins 
[02:36:10] [Server thread/INFO] [minecraft/DedicatedServer]: Plugins (9): Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, Inventory Sync, JdaLibraryLoader, LuckPerms, UltimateChat, spark
```

#### Your most recent log or stack trace file where the issue was present: 

In this [log](https://gist.github.com/bluelightning32/a2d2561ac27172d5e2578e9aa1d82618), you can see the player logs off, then a server backup is started.

I copied the hex data from the mysql database:
```
$ mysql --binary-as-hex -uminecraft -p
MariaDB [dd_ss_invsync]> use dd_ss_invsync;
MariaDB [dd_ss_invsync]> SELECT * FROM invsync_inventories where UUID=0x8189ca6f92524683ac29556125d44470\G
```

I converted the hex string into a binary file:
```
$ xxd -r -p 2019-03-16-00\:04\:42.txt > 2019-03-16-00\:04\:42.dat
```

I dumped the nbt data from inside it, and it shows the flower bag is empty:
```
$ cat ~/.local/bin/nbtutil 
#!/bin/bash
TERM=xterm mono $HOME/nbtexplorer/NBTUtil.exe "$@"
$ nbtutil --path 2019-03-16-00:04:42.dat --printtree
...
   |   + 2 entries
   |   | + slot: 4
   |   | + stack: 4 entries
   |   |   + ContentVersion: 1
   |   |   + Count: 1
   |   |   + UnsafeDamage: 0
   |   |   + ItemType: botania:flowerbag
   |   + 2 entries
```

However the player.dat file I restored from the backup shows the bag is non-empty:
```
$  nbtutil --path 8189ca6f-9252-4683-ac29-556125d44470.dat --printtree
   | + 5 entries
   | | + Count: 1
   | | + Slot: 4
   | | + Damage: 0
   | | + id: botania:flowerbag
   | | + ForgeCaps: 2 entries
   | |   + Parent: 16 entries
   | |   | + 4 entries
   | |   | | + Count: 4
   | |   | | + Damage: 0
   | |   | | + Slot: 0
   | |   | | + id: botania:flower
   | |   | + 4 entries
   | |   | | + Count: 12
   | |   | | + Damage: 1
   | |   | | + Slot: 1
   | |   | | + id: botania:flower
...
```

Later the player was able to reproduce the problem with just the flower bag in their inventory.

**Comment by BrainStone** [comment] 2019-03-16 10:03
Can you please enable debug in the InvSync config and upload the debug.log after reproducing the bug? Preferably just reproducing it once.

**Comment by bluelightning32** [comment] 2019-03-16 10:15
The log above was with debug enabled. Something else in the player's inventory broke the json printing.

Here is the debug log from when the player reproduced it with just the flower bag in their inventory (with one flower inside):
```
[02:19:14] [Server thread/INFO] [invsync]: {"version":1,"inventory":{"inventory":[{"slot":8,"stack":{"ContentVersion":1,"ItemType":"botania:flowerbag","Count":1,"UnsafeDamage":0}}],"selectedSlot":8},"ender_chest":{"data":[]},"game_mode":{"data":"minecraft:survival"},"experience":{"experience_level":5,"experience_since_level":15},"health":{"data":40.0},"hunger":{"food_level":10,"saturation":1.0},"mod.baubles":{"data":[]},"mod.cyclicmagic":{"crafting_capability":false,"inventory_capability":false,"inventory":[]},"mod.spiceoflife":{"data":{"spiceoflifeHistory":{"History":{"Foods":[{"WorldTime":133549963,"Hunger":2,"PlayerTime":8231109,"Saturation":0.05,"id":"rustic:cloudsbluff","Count":11,"Damage":0},{"WorldTime":133695354,"Hunger":2,"PlayerTime":8233887,"Saturation":0.05,"id":"rustic:wildberries","Count":44,"Damage":0},{"WorldTime":133695371,"Hunger":2,"PlayerTime":8233904,"Saturation":0.05,"id":"rustic:wildberries","Count":43,"Damage":0},{"WorldTime":133695388,"Hunger":2,"PlayerTime":8233921,"Saturation":0.05,"id":"rustic:wildberries","Count":42,"Damage":0},{"WorldTime":133695405,"Hunger":2,"PlayerTime":8233938,"Saturation":0.05,"id":"rustic:wildberries","Count":41,"Damage":0},{"WorldTime":133695423,"Hunger":2,"PlayerTime":8233956,"Saturation":0.05,"id":"rustic:wildberries","Count":40,"Damage":0}]}}}}}
```

**Comment by bluelightning32** [comment] 2019-03-16 10:19
I think the problem is that InvSync is [using](https://github.com/AuraDevelopmentTeam/InvSync/blob/832b056dcb3fa9afd2774b263be8f587e54806ec/src/main/java/world/jnc/invsync/util/serializer/InventorySerializer.java#L82) [toContainer](https://github.com/SpongePowered/SpongeCommon/blob/cd5ff6beb7850b7b75451b35530a3b18a99a935e/src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackSnapshot.java#L186) to serialize the object. However the flowerbag is storing its contents in the `ForgeCaps` tag, which toContainer is ignoring.

**Comment by BrainStone** [comment] 2019-03-16 10:36
Which would mean that either the bag is programmed badly or it is a Sponge issue. I’ll investigate later today. I have a feeling this will end up on the Sponge issue tracker.

**Comment by BrainStone** [comment] 2019-03-22 23:49
Turns out this is indeed a SpongeForge issue: SpongePowered/SpongeForge#2656. So I will close this, as there's nothing I can do on my side. Once the issue is resolved in SpongeForge, this will work.

**Comment by BrainStone** [comment] 2019-03-29 19:36
@bluelightning32 it should be fixed now in the latest SF.

**Comment by bluelightning32** [comment] 2019-03-30 03:17
I tested with SpongeForge version 1.12.2-2768-7.1.6-RC3634. I did the following:
1. Logged into the server
2. Used creative mode to give myself a flower bag with 1 flower inside it.
3. Logged out. The debug.log shows that the flower bag contents were serialized.
4. Logged back in. InvSync restored my flower bag, but it was empty!
5. Logged out. The debug.log shows that the flower bag is empty.

[debug.log](https://gist.github.com/bluelightning32/c5697d359f1f725d27c55befb9002efa)

**Comment by bluelightning32** [comment] 2019-04-06 08:11
Any updates? Should I retest?

**Comment by BrainStone** [comment] 2019-04-06 08:35
I’ll have to ask gabizou. Though I don’t think so.

**Comment by bluelightning32** [comment] 2019-04-14 23:00
Please reopen this bug, because it is still reproducing.

**Comment by BrainStone** [comment] 2019-04-14 23:01
It’s still a SpongeForge issue.

**Closed** 2019-05-10 06:37 UTC
Labels: external issue
